<?php

/**
 * This is the model base class for the table "category".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Category".
 *
 * Columns in table "category" available as properties of the model,
 * followed by relations of table "category" available as properties of the model.
 *
 * @property string $intCategoryID
 * @property string $varTitle
 * @property integer $isActive
 *
 * @property News[] $news
 * @property NewsPublic[] $newsPublics
 */
abstract class BaseCategory extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'category';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Category|Categories', $n);
	}

	public static function representingColumn() {
		return 'varTitle';
	}

	public function rules() {
		return array(
			array('varTitle', 'required'),
			array('isActive', 'numerical', 'integerOnly'=>true),
			array('varTitle', 'length', 'max'=>255),
			array('isActive', 'default', 'setOnEmpty' => true, 'value' => null),
			array('intCategoryID, varTitle, isActive', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'news' => array(self::HAS_MANY, 'News', 'intCategoryID'),
			'newsPublics' => array(self::HAS_MANY, 'NewsPublic', 'intCategoryID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'intCategoryID' => Yii::t('app', 'Int Category'),
			'varTitle' => Yii::t('app', 'Var Title'),
			'isActive' => Yii::t('app', 'Is Active'),
			'news' => null,
			'newsPublics' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('intCategoryID', $this->intCategoryID, true);
		$criteria->compare('varTitle', $this->varTitle, true);
		$criteria->compare('isActive', $this->isActive);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}