<?php

/**
 * This is the model base class for the table "news_public".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NewsPublic".
 *
 * Columns in table "news_public" available as properties of the model,
 * followed by relations of table "news_public" available as properties of the model.
 *
 * @property string $intNewPublicID
 * @property string $intEditionID
 * @property string $intNewID
 * @property string $varText
 * @property string $varTitle
 * @property string $varTizer
 * @property string $varMailText
 * @property integer $isFree
 * @property integer $isPublic
 * @property string $intCategoryID
 *
 * @property Editions $editions
 * @property NewsComments[] $newsComments
 * @property Category $intCategory
 * @property NewsPublicGallery[] $newsPublicGalleries
 * @property NewsRating[] $newsRatings
 */
abstract class BaseNewsPublic extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'news_public';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'NewsPublic|NewsPublics', $n);
	}

	public static function representingColumn() {
		return 'varText';
	}

	public function rules() {
        return array(
            array('intEditionID, intNewID, varText, varTitle, varTizer, varMailText, intCategoryID', 'required'),
            array('isFree, isPublic', 'numerical', 'integerOnly'=>true),
            array('intEditionID, intNewID, intCategoryID', 'length', 'max'=>10),
            array('varTitle, varTizer', 'length', 'max'=>255),
            array('isFree, isPublic', 'default', 'setOnEmpty' => true, 'value' => null),
            array('intNewPublicID, intEditionID, intNewID, varText, varTitle, varTizer, varMailText, isFree, isPublic, intCategoryID', 'safe', 'on'=>'search'),
        );
	}

	public function relations() {
        return array(
            'editions' => array(self::BELONGS_TO, 'Editions', 'intEditionID'),
            'newsComments' => array(self::HAS_MANY, 'NewsComments', 'intNewPublicID'),
            'intCategory' => array(self::BELONGS_TO, 'Category', 'intCategoryID'),
            'newsPublicGalleries' => array(self::HAS_MANY, 'NewsPublicGallery', 'intNewPublicID'),
            'newsRatings' => array(self::HAS_MANY, 'NewsRating', 'intNewPublicID'),
        );
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'intNewPublicID' => Yii::t('app', 'Int New Public'),
			'intNewID' => Yii::t('app', 'Int New'),
			'varText' => Yii::t('app', 'Var Text'),
			'varTitle' => Yii::t('app', 'Var Title'),
			'varTizer' => Yii::t('app', 'Var Tizer'),
			'varMailText' => Yii::t('app', 'Var Mail Text'),
			'isFree' => Yii::t('app', 'Is Free'),
			'isPublic' => Yii::t('app', 'Is Public'),
			'intCategoryID' => null,
			'newsComments' => null,
			'intCategory' => null,
			'newsPublicGalleries' => null,
			'newsRatings' => null,
		);
	}

}