<?php

/**
 * This is the model base class for the table "news_gallery".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NewsGallery".
 *
 * Columns in table "news_gallery" available as properties of the model,
 * followed by relations of table "news_gallery" available as properties of the model.
 *
 * @property string $intPhotoID
 * @property string $intNewID
 * @property string $name
 * @property string $varHash
 *
 * @property News $intNew
 */
abstract class BaseNewsGallery extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'news_gallery';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'NewsGallery|NewsGalleries', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('intNewID, name', 'required'),
			array('intNewID', 'length', 'max'=>10),
			array('name', 'length', 'max'=>50),
			array('varHash', 'length', 'max'=>32),
			array('varHash', 'default', 'setOnEmpty' => true, 'value' => null),
			array('intPhotoID, intNewID, name, varHash', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
			'intNew' => array(self::BELONGS_TO, 'News', 'intNewID'),
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'intPhotoID' => Yii::t('app', 'Int Photo'),
			'intNewID' => null,
			'name' => Yii::t('app', 'Name'),
			'varHash' => Yii::t('app', 'Var Hash'),
			'intNew' => null,
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('intPhotoID', $this->intPhotoID, true);
		$criteria->compare('intNewID', $this->intNewID);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('varHash', $this->varHash, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}