<?php

/**
 * This is the model base class for the table "news_rating_subscribers".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "NewsRatingSubscribers".
 *
 * Columns in table "news_rating_subscribers" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $intNRSID
 * @property string $intEditionID
 * @property string $intNewPublicID
 * @property string $intSubID
 * @property integer $intRaiting
 *
 */
abstract class BaseNewsRatingSubscribers extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'news_rating_subscribers';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'NewsRatingSubscribers|NewsRatingSubscribers', $n);
	}

	public static function representingColumn() {
		return 'intNRSID';
	}

	public function rules() {
		return array(
			array('intEditionID, intNewPublicID, intSubID, intRaiting', 'required'),
			array('intRaiting', 'numerical', 'integerOnly'=>true),
			array('intEditionID, intNewPublicID, intSubID', 'length', 'max'=>10),
			array('intNRSID, intEditionID, intNewPublicID, intSubID, intRaiting', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'intNRSID' => Yii::t('app', 'Int Nrsid'),
			'intEditionID' => Yii::t('app', 'Int Edition'),
			'intNewPublicID' => Yii::t('app', 'Int New Public'),
			'intSubID' => Yii::t('app', 'Int Sub'),
			'intRaiting' => Yii::t('app', 'Int Raiting'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('intNRSID', $this->intNRSID, true);
		$criteria->compare('intEditionID', $this->intEditionID, true);
		$criteria->compare('intNewPublicID', $this->intNewPublicID, true);
		$criteria->compare('intSubID', $this->intSubID, true);
		$criteria->compare('intRaiting', $this->intRaiting);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}